version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: orcamento-postgres
    environment:
      POSTGRES_DB: orcamentodb_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: orcamento_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orcamentodb_api
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_PROFILE: docker

volumes:
    pgdata: